### ISSUE TITLE
Relog bug

### ISSUE THREAD

**Issue by DKrolls** [GamerKing195/Thirst#10]
Logging out and back in causes thirst to be replenished.

**Comment by cadenkriese** [comment]
Hello, please send me the SQL section of your config, thirst_data.yml, and any errors that have occurred in the console.

**Comment by cadenkriese** [comment]
That info is no longer required, I've duplicated the bug, working on a fix ASAP.

**Comment by cadenkriese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Thirst is reset on player relog.](https://trello.com/c/bThEQvWP/46-fix---thirst-is-reset-on-player-relog)

**Comment by cadenkriese** [comment]
This issue has been fixed in version 1.8.8 found [here](https://www.spigotmc.org/resources/thirst.24610/update?update=166234).
