### ISSUE TITLE
Block-Drink-Delay is not actually a float

### ISSUE THREAD

**Issue by DKrolls** [GamerKing195/Thirst#11]
I tried the value 1.1 and after /thirst reload the console complained about an improperly formatted YAML. I ran it through a lint to make sure it was OK before posting this. It appears to my limited testing that it's looking for an int value as opposed to a float.

**Comment by cadenkriese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Block-Drink-Delay is not float.](https://trello.com/c/BHlxo54M/45-fix---block-drink-delay-is-not-float)

**Comment by cadenkriese** [comment]
This issue has been fixed in version 1.8.8 found here.
