### ISSUE TITLE
Drink-Block-Water spams player when refilling thirst bar

### ISSUE THREAD

**Issue by DKrolls** [GamerKing195/Thirst#13]
Players at 0 thirst get spammed while filling up while submerged underwater with messages like:
"Watch out your thirst is at 1%!"
"Watch out your thirst is at 2%!"
"Watch out your thirst is at 3%!"
"Watch out your thirst is at 4%!"
"Watch out your thirst is at 5%!"
etc...
All you have to do to recreate it is get to 0 thirst, set Drink-Block-Water to true and sit underwater.
![2017-06-06_13 29 34](https://user-images.githubusercontent.com/12780812/26845529-5554ecb0-4abc-11e7-851e-010e2f511ecd.png)

**Comment by cadenkriese** [comment]
Hi there, you can get rid of these messages by setting critical-thirst-percent to 0 in the config, although I could change the plugin to only display the messages while thirst is going down if that is what you're asking for.

**Comment by DKrolls** [comment]
Yes, that is what I'm looking for. Thank you.

**Comment by cadenkriese** [comment]
Alright I have that coded, just curious if you have any more feature requests, since this is a pretty small update as of now.

**Comment by DKrolls** [comment]
Nah that's all. Thank you.

**Comment by cadenkriese** [comment]
Alright, I'll debug and publish not using Trello for this one because it's so tiny.

**Comment by cadenkriese** [comment]
Fixed in version 1.8.10 available [here](https://www.spigotmc.org/resources/thirst.24610/update?update=166374). I apologize for this taking longer than I thought I got tripped up by another bug I was fixing. Please give the auto-updater up to two hours to refresh the spigot site cache before it notifies you of the update.
