### ISSUE TITLE
%gkthirst_thirstremoval% seems not to work

### ISSUE THREAD

**Issue by TrademarkTM** [GamerKing195/Thirst#16]
Hello!
I am using thirst placeholders for scoreboard, but as the title says, %gkthirst_thirstremoval% doesn't work.

%gkthirst_thirstpercent% works fine, tho.
http://prntscr.com/g4r9uz

**Comment by cadenkriese** [comment]
Hello, that placeholder has been recently changed, I apologize for not correcting the documentation on the main page of Thirst, that has now been corrected, but the thirstremoval variable turned into thirstremovalspeed and thirstremovalamount in a recent update.

Once again, I apologize for the lack of documentation, I hope this fixes all of your issues, however, feel free to ask if you have any questions/concerns.

       ~ Gamer
