### ISSUE TITLE
Spigot version not compatible

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [GamerKing195/Thirst#21]
12:50:35 Thirst: config.yml & thirst_data.yml successfully reloaded!
12:50:35 CONSOLE: ERROR]: [Thirst] [Thirst V1.9.6] Your Spigot version is not compatible with the Bossbar display type, please use version 1.9 or higher.
12:50:35 CONSOLE: ERROR]: [Thirst] [Thirst V1.9.6] Changing to display type ACTION...

I'm using MC Spigot 1.12
I use RPGPlayerLeveling too...
could u check ?

**Comment by cadenkriese** [comment]
Hey there thanks for the bug report, I should've fixed this issue in version 1.9.7, found [here](https://www.spigotmc.org/resources/thirst.24610/update?update=189206).
