### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [GamerKing195/Thirst#23]
I'm trying the latest version of thirst after the mega bugfix of the crash.

But the bossbarr still doesn't work. I change it, but the plugin put it automatically in ACTION bAR

**Comment by cadenkriese** [comment]
Hey there, mind telling me your server version again and then any logs if you have them, I'm assuming you're using V1.9.7 of thirst.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
it is telling me that 1.9.7 does not match latest version 2.7.4

**Comment by cadenkriese** [comment]
Could you please send the whole error copied & pasted please

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
There is not errors... just the bossbar doen't work.

If I change the config in bossbarr... the plugin automatically change it in actionbar.

**Comment by cadenkriese** [comment]
Okay, what version of Spigot are you using?

**Comment by cadenkriese** [comment]
Hello, I've actually fixed it now (and tested it so you should be good to go). Very sorry for the rough time you've had with this plugin, hopefully this begins to fix that reputation, thanks again for the report.

New update can be found [here](https://www.spigotmc.org/resources/thirst.24610/update?update=192773).

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
The bossbarr now works... but it doesn't appear when it changes..

thirst version 1.9.8

Could u tell me how it works? It should be showed when the thirst changes....??
the boss bar doesn't appear when it changes

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Did u tryed it?

**Comment by cadenkriese** [comment]
Yes I tested it multiple times are you sure you installed the update correctly & setup the config correctly?

**Comment by cadenkriese** [comment]
Referring to "did you setup the config correctly" do you have it set to only display when the thirst changes and does it send the messages in console?

I'll see if I can finally fix this tonight, also if you have any feature requests major or minor I'll be sure to add them as an apology for all the troubles you're having with the plugin.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
`# #################################
#                                 #
# Thirst V1.9.8, by GamerKing195#
#                                 #
# #################################
# 
# Config Guide:
# 
# STRING, Any text you want.
# INT, A number without a decimal.
# FLOAT, A number with a decimal.
# BOOLEAN, A string that either equals true or false.
# ARRAY, A list of values like those stated above.

# ---------------General---------------
# 
# REMOVE_THIRST
# Desc: The amount of thirst that will be removed every THIRST_DELAY
# Type: int (100 or lower.)
# Default: 1
Remove-Thirst: 1
# 
# CRITICAL_THIRST_PERCENT
# Desc: The percent at which a players thirst becomes critical and the THIRST_LOW_MESSAGE and !!! will be displayed.
# Type: Integer
# Default: 10
Critical-Thirst-Percent: 10
# 
# THIRST_DELAY
# Desc: The delay in seconds before thirst is removed from every player.
# Type: float (Time in seconds)
# Default: 36 (will remove 100% over three days, just like in real life!)
# Note: This does support values under one second without any changes in lag!
Thirst-Delay: 36.0
# 
# THIRST_QUENCHING_ITEM
# Desc: The item that will quench the thirst of a player.
# Type: Formatted string array
# Default:
# - POTION=20
# - GOLDEN_APPLE:1=100
# Requirements: Should be in format: ITEM:METADATA=PERCENT(metadata optional)
Thirst-Quenching-Items:
- POTION=20
- GOLDEN_APPLE:1=100
# 
# IGNORE_CREATIVE
# Desc: If true, anyone in creative will not be affected by Thirst.
# Type: Boolean
# Default: true
Ignore-Creative: true
# 
# IGNORE_OP
# Desc: If true, anyone who is opped will not be affected by Thirst.
# Type: Boolean
# Default: false
Ignore-OP: false
# 
# DRINK_BLOCK_WATER
# Desc: If true, players will recover 2% of their thirst every second, if they are swimming in water.
# Type: Boolean
# Default: false
Drink-Block-Water: true
# 
# BLOCK_DRINK_DELAY
# Desc: Time in seconds between when players gain 1 Thirst from being under water.
# Type: Float (Seconds)
# Default: 1
Block-Drink-Delay: 1.0
# 
# REMOVE_THIRST_SUBMERGED
# Desc: If true, the player will still be affected by thirst while they are underwater..
# Type: boolean
# Default: false
Remove-Thirst-Submerged: false
# 
# ENABLE_UPDATER
# Desc: If true, the auto-updater will ping the spigot site and alert you about new updates, and even automatically install them.
# Note: If set to false you can still install updates via /thirst update.
# Type: Boolean
# Default: true
Enable-Updater: false
# 
# REMOVE_WHEN_AFK
# Desc: If false, thirst will not remove thirst whenever the player hasn't moved since their last removal of thirst.
# Type: Boolean
# Default: true
Remove-When-AFK: true
# 
# ALLOW_ITEM_CONSUMPTION
# Desc: If false, thirst will not allow players to consume any THIRST_QUENCHING_ITEMS, if their thirst is at 100%.
# Type: Boolean
# Default: true
Allow-Item-Consumption: true
Display:
  # ---------------Display---------------
  # 
  # DISPLAY_TYPE
  # Desc: Changes the way players see their thirst.
  # Type: Enum
  # Possible types: SCOREBOARD, ACTION, COMMAND, BOSSBAR
  # Default: ACTION
  # Note: The command /thirst view, and /thirst view %player% will always be enabled, use command to disable scoreboard, and action.
  Display-Type: BOSSBAR
  # 
  # BAR_COLOR
  # Desc: The colors for the bossbar, if that display type is chosen.
  # Type: Enum
  # Possible types: BLUE, GREEN, PINK, PURPLE, RED, YELLOW, WHITE
  # Default: BLUE
  Bar-Color: BLUE
  # 
  # BAR_STYLE
  # Desc: The style for the bossbar, if that display type is chosen.
  # Type: Enum
  # Possible types: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  # Default: SOLID
  Bar-Style: SOLID
  # 
  # USE_BAR_PROGRESS
  # Desc: Should the bossbar progress mimic that of the players thirst.
  # Type: Boolean
  # Default: FALSE
  Use-Bar-Progress: false
  # 
  # ALWAYS_SHOWING
  # Desc: If set to false thirst will only display when a players thirst changes.
  # Type: Boolean
  # Default: false
  # Notes: For scoreboards & bossbar it will make the scoreboard pop up for 3 seconds then go away.
  Always-Showing: false
Multipliers:
  # ---------------Multipliers---------------
  # 
  # BIOMES
  # Desc: List all biomes you want to modify players thirst percent. Ex: desert.5 will make players thirst go down 5 seconds quicker
  # Type: Formatted string array
  # Default:
  # DESERT.5
  # HELL.10
  Biomes:
  - DESERT.5
  - HELL.10
  # 
  # ARMOR
  # Desc: List all armor types you want to modify players thirst percent. Ex: leather.5 will make players thirst go down 5 seconds quicker in full leather armor
  # Type: Formatted string array
  # Default:
  # LEATHER.5
  # IRON_CHESTPLATE.10
  Armor:
  - LEATHER.5
  - IRON_CHESTPLATE.10
  # 
  # SPRINT
  # Desc: How much quicker you want thirst to be removed when sprinting, put -1 to make no thirst removed.
  # Type: Integer
  # Default: -1
  Sprint: 2
  # 
  # DAY
  # Desc: How much quicker you want thirst to be removed when it is day, put 0 for no change, put negative to make thirst take longer to be removed.
  # Type: Integer
  # Default: 0
  Day: 0
  # 
  # NIGHT
  # Desc: How much quicker you want thirst to be removed when it is night, put 0 for no change, put negative to make thirst take longer to be removed.
  # Type: Integer
  # Default: 0
  Night: 0
  # 
  # SUNNY
  # Desc: How much quicker you want thirst to be removed when it is sunny, put 0 for no change, put negative to make thirst take longer to be removed.
  # Type: Integer
  # Default: 0
  Sunny: 2
  # 
  # RAIN
  # Desc: How much quicker you want thirst to be removed when it is raining, put 0 for no change, put negative to make thirst take longer to be removed.
  # Type: Integer
  # Default: 0
  Rain: -2
Effects:
  # ---------------Potions---------------
  # 
  # ENABLED
  # Desc: If false, all potion effects will not be given.
  # Type: Boolean
  # Default: true
  Enabled: true
  # 
  # EFFECTS
  # Desc: The effects that will be applied on low thirst.
  # Type: Formatted string array
  # Default:
  # - CONFUSION.30.1.10.0
  # - DAMAGE.2.3.0.0
  # Requirements: Should be in format 'POTIONEFFECT.DURATION-IN-SECONDS.AMPLIFIER.MAX-PERCENT.MIN-PERCENT'
  # Note: To damage a player use this format DAMAGE.DELAY-IN-SECONDS.AMOUNT.MAX-PERCENT.MIN-PERCENT.
  # (Amount is how much damage will be done out of 20)
  # Note: The max percent and min percent are to specify a range for the effect, this can be used to give
  # speed when the player has over 90 thirst or to increase the strength of an effect as thirst decreases.
  Potions:
  - CONFUSION.30.1.10.0
  - DAMAGE.2.3.0.0
Messages:
  # ---------------Messages---------------
  # 
  # THIRST_MESSAGE
  # Desc: Changes the message displayed in the display_type.
  # Type: String
  # Variables: %thirstbar%, %percent%, %player%, %removespeed%
  # Default: &bTHIRST &f- &8[%thirstbar%&8] %percent%
  # Notes: %removespeed% will not work if you are viewing an offline players thirst. It will be replaced with nothing.
  ThirstMessage: '&b&lSete &f- &8[%thirstbar%&8] %percent%'
  # 
  # THIRST_LOW_MESSAGE
  # Desc: The message that will be displayed to a player when their thirst is below the critical thirst amount.
  # Type: String
  # Variables: %percent%, %player%
  # Default: &8[&bThirst&8] &aWatch out &e%player%, &ayour thirst is at &e%percent%!
  ThirstLowMessage: '&8[&1Sete&8] &bAttenzione &f%player%, &bla tua sete e'' al &f%percent%!'
  # 
  # THIRST_DEATH_MESSAGE
  # Desc: The message that will be sent when a player dies of thirst.
  # Type: String
  # Variables: %player%
  # Default: &f%player% didn't drink his water bottle.
  Thirst-Death-Message: '&f%player% e'' morto di sete.'
  # 
  # THIRST_VIEW_PLAYER_MESSAGE
  # Desc: The message that will be sent when someone does /thirst view %player%
  # Type: String
  # Variables: %player%, %thirstbar%, %percent%, %thirstmessage%, %removespeed%
  # Default: &f%player%'s &bthirst: %thirstmessage%
  # Notes: %removespeed% will not work if you are viewing an offline players thirst. It will be replaced with nothing.
  # NOTICE: This is not the message displayed when a player runs /thirst view, the message run then is Thirst-View-Message.
  Thirst-View-Player: '&8[&1Sete&8] &bSete di &f%player%&b: %thirstmessage%'
  # 
  # THIRST_VIEW_MESSAGE
  # Desc: The message sent when a player does /thirst view
  # Type: String
  # Variables: %player%, %bar%, %percent%, %thirstmessage%, %removespeed%
  # Default: &8[&1Thirst&8] &bYour thist: %thirstmessage%
  Thirst-View-Message: '&8[&1Sete&8] &bLa tua sete: %thirstmessage%'
  # 
  # ITEM_CONSUME_MESSAGE
  # Desc: The message sent when a player tries to consume a THIRST_QUENCHING_ITEM on 100% thirst with ALLOW_ITEM_CONSUMPTION set to false.
  # Type: String
  # Variables: %player%
  # Default: &8[&1Thirst&8] &bYou cannot consume that while your Thirst is full!
  Item-Consume-Message: '&8[&1Sete&8] &bYou cannot consume that while your Thirst
    is full!'
  # 
  # INVALID_COMMAND_MESSAGE
  # Desc: The message that wil be sent when someone does /thirst view %player% with an invalid playername.
  # Type: String
  # Default: &8[&1Thirst&8] &bInvalid command syntax!
  Invalid-Command-Message: '&8[&1Sete&8] &bSintassi di comando non valida!'
  # 
  # NO_PERMISSION_MESSAGE
  # Desc: The message that will be sent when a player does not have permission to do something.
  # Type: String
  # Default: &8[&1Thirst&8] &bYou do not have permission to do that!
  No-Permission-Message: '&8[&1Sete&8] &bNon hai il permesso di farlo!'
  # 
  # SCOREBOARD_NAME
  # Desc: Only applies if display_type is set to SCOREBOARD.
  # Type: String
  # Variables: %player%
  # Default: &f&lTHIRST
  Scoreboard-Title: '&f&lSete'
DisabledAreas:
  # ---------------Disabled Areas---------------
  # 
  # DISABLED_WORLDS
  # Desc: List all of the worlds that will be unaffected by thirst.
  # Type: String Array
  # Default: []
  Disabled-Worlds:
  - Builder
  # 
  # DISABLED_REGIONS
  # Desc: List all of the world guard regions that will be unaffected by thirst.
  # Type: String Array
  # Default: []
  Disabled-Regions:
  - Lotus
SQL:
  # ---------------SQL Database---------------
  # 
  # ENABLE_SQL
  # Desc: Should thirst data be stored in a MySQL database so you can sync thirst between servers.
  # Type: boolean
  # Default: false
  Enable-Sql: false
  # 
  # HOST_NAME
  # Desc: Hostname / IP to the MySQL db.
  # Type: sting
  Hostname: 0.0.0.0
  # 
  # USERNAME
  # Desc: Username Thirst  will use to connect to the database.
  # Type: boolean
  Username: root
  # 
  # PASSWORD
  # Desc: Password Thirst will use to connect to the database.
  # Type: boolean
  Password: '1234'
  # 
  # DATABASE
  # Desc: The database that Thirst will store its table in.
  # Type: boolean
  Database: db
  # 
  # TABLENAME
  # Desc: The name of the table Thirst will store data in.
  # Type: boolean
  Tablename: thirst
`

**Comment by cadenkriese** [comment]
Hello again,

Try setting Always-Showing to true and see if that delivers the mechanic you want.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
But I don’t want that the bossbar is always showed. I want that  it come out only when the thirst level change.

**Comment by cadenkriese** [comment]
Okay I'll test out the bossbar with always enabled set to false later today and try and get another fix out.

**Comment by cadenkriese** [comment]
I've looked into this more and made yet another bugfix V1.9.9 found [here](https://www.spigotmc.org/resources/thirst.24610/update?update=193323).
