### ISSUE TITLE
Thirst not damaging players

### ISSUE THREAD

**Issue by gerbillover** [GamerKing195/Thirst#24]
For some reason, Thirst refuses to damage players when told to in the config.yml. As you can see here in my config.yml, I have it set to damage players for 2 health every 2 seconds, when their thirst reaches 2% or lower. However, it just doesn't happen. I've checked my logs and no errors have turned up. None on startup either, I don't exactly know what's going on here.

Note that the other two potion effects listed work perfectly fine, and I am using Thirst 1.9.9.

The important part of the config.yml:

`   ---------------Potions---------------
   
   ENABLED
    Desc: If false, all potion effects will not be given.
    Type: Boolean
    Default: true
  Enabled: true
   
   EFFECTS
    Desc: The effects that will be applied on low thirst.
    Type: Formatted string array
   Default:
    - CONFUSION.30.1.10.0
    - DAMAGE.2.3.0.0
    Requirements: Should be in format 'POTIONEFFECT.DURATION-IN-SECONDS.AMPLIFIER.MAX-PERCENT.MIN-PERCENT'
    Note: To damage a player use this format DAMAGE.DELAY-IN-SECONDS.AMOUNT.MAX-PERCENT.MIN-PERCENT.
    (Amount is how much damage will be done out of 20)
    Note: The max percent and min percent are to specify a range for the effect, this can be used to give
    speed when the player has over 90 thirst or to increase the strength of an effect as thirst decreases.
  Potions:
  - DAMAGE.2.2.2.0
  - CONFUSION.30.1.10.0
  - SLOW.30.1.10.0`

**Comment by cadenkriese** [comment]
Hey there, looks like in your config you have it set to apply damage when their thirst reaches 0, change the second to last number to a 2 to have it go at 2%.

EDIT:
DIdn't see you already had that I was looking at the defaults :P

I'll look into this later today if I have time.

**Comment by cadenkriese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Damage effect.](https://trello.com/c/0iJuC5wL/63-fix-damage-effect)

**Comment by cadenkriese** [comment]
Hello again, this issue has been fixed in V1.9.10 found [here](https://www.spigotmc.org/resources/thirst.24610/update?update=199782).
