### ISSUE TITLE
Error, please fix.

### ISSUE THREAD

**Issue by ColorsASD** [GamerKing195/Thirst#29]
Hi.

Error 1: https://pastebin.com/G0qnaR8b

Error 2: https://pastebin.com/FyGfgBg3

**Comment by cadenkriese** [comment]
Hey there thanks for the report, however some context to the error like when it occurred and what it affected would be nice.

**Comment by ColorsASD** [comment]
Error 1: occasionally at player connection ([19:16:03] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Thirst v1.9.11)
Error 2: [18:42:05] [Server thread/ERROR]: [Thirst] PLUGIN MESSAGE: Error occurred while running MySQL statement.

Random, occasionally.
There is nothing more to say about this.
SQL part can be an error. (see code)

**Comment by ColorsASD** [comment]
One theory: Join a player, not get the right information for SQL.

**Comment by ColorsASD** [comment]
sorry i'm not english
