### ISSUE TITLE
ignoring the operator's thirst is it possible to turn off ?

### ISSUE THREAD

**Issue by ghost** [GamerKing195/Thirst#30]
ignoring the operator's thirst is it possible to turn off ?

**Comment by cadenkriese** [comment]
There is a config node for it yes.

**Comment by ghost** [comment]
I searched but found nothing...

**Comment by cadenkriese** [comment]
In the general section under ignore creative there is ignore op.

**Comment by ghost** [comment]
I can't find this in the config

**Comment by cadenkriese** [comment]
Please send me your config file.

**Comment by ghost** [comment]
[config.txt](https://github.com/fl0gic/Thirst/files/2211051/config.txt)

**Comment by cadenkriese** [comment]
That is not the config file for this plugin.

**Comment by ghost** [comment]
what do you mean ?

**Comment by cadenkriese** [comment]
I mean that's not the config for this plugin you are using a different Thirst plugin.

**Comment by ghost** [comment]
can you tell me how they are different ?

**Comment by cadenkriese** [comment]
No Im not the Dev of the other l have no idea what the differences are.
