### ISSUE TITLE
Have Thirst disables in other worlds

### ISSUE THREAD

**Issue by Charthulu** [GamerKing195/Thirst#6]
Hey there,

I really like the idea of this plugin. however i can't seem to change too much about it, for example, Disable it in other world, have a command to disable it for a player. 

i have PerWorldPlugin installed, and it seems like the plugin suports it, but whenever i change worlds i still get the effects and it still drains my water level, but i cannot gain water level.

I hope you can help

Thanks

**Comment by cadenkriese** [comment]
Hello, disabling thirst in other worlds is already a configurable option found in the config.yml file. You may add the name of the world you wish to disable like so.

DisabledWorlds: 
   - nothirst_world
